### PR TITLE
Translated into Portuguese from Brazil

### PR DESCRIPTION
**Pull request by BrunoMine**
This will help the Brazilian developers to internationalize their mods.

### CODE REVIEW

**Comment by sofar** [comment]
@kaeza are you OK with this? This is kind of a meta-translation effort. I realize that this is useful to some, but I'm not sure whether you want this info here or on a wiki instead.

**Comment by kaeza** [comment]
@sofar It's fine as a README.

Cc: @ShadowNinja

**Comment by ShadowNinja** [comment]
Seems fine to me.

**Comment by sofar** [comment]
f80ae5684f390af7d888fd8ecd1478eb1275bede

**Comment by sofar** [comment]
I left out the changes to README.txt. That rename was already done.

**Pull request closed without merging**
